<?php

namespace App\Listeners;

use Illuminate\Auth\Events\Login;
use Modules\Ordering\Services\CartService;

class MergeGuestCartOnLogin
{
    public function __construct(private CartService $cartService) {}

    public function handle(Login $event): void
    {
        // After login, the session ID has been regenerated by SessionGuard::login().
        // We use the pre-login session ID that was saved by the Attempting event listener.
        $sessionId = session('_guest_cart_sid');

        if ($sessionId) {
            $this->cartService->mergeGuestCart($event->user, $sessionId);
            session()->forget('_guest_cart_sid');
        }
    }
}
